#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DEADLY_GHOULS_REPO == "DEADLY-GHOULS-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RlYWRseS1maWdodGVycy9ERUFETFktR0hPVUxTLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlwIA==" | base64 -d
    elif [[ $DEADLY_GHOULS_REPO == "DEADLY-GHOULS-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RlYWRseS1maWdodGVycy9ERUFETFktR0hPVUxTLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlwIA==" | base64 -d
    elif [[ $DEADLY_GHOULS_REPO =~ $regex ]]
    then
        if [[ $DEADLY_GHOULS_REPO_BRANCH ]]
        then
            echo "${DEADLY_GHOULS_REPO}/archive/${DEADLY_GHOULS_REPO_BRANCH}.zip"
        else
            echo "${DEADLY_GHOULS_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2RlYWRseS1maWdodGVycy9ERUFETFktR0hPVUxTLVVTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlwIA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="DeadlyGhouls-Bot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    DEADLYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $DEADLYPATH
    echo "    Starting DeadlyGhouls-Bot    "
    echo "
                         DeadlyGhouls-Bot
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
